# Generated by Django 6.0 on 2025-12-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_remove_carouselitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon_url',
            field=models.URLField(blank=True, help_text='DevIcon URL from https://devicon.dev or similar source', null=True),
        ),
    ]
