# Generated by Django 6.0 on 2025-12-24 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_technology_icon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='icon_url',
        ),
    ]
