# Generated by Django 6.0 on 2025-12-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_remove_technology_icon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='emoji',
        ),
    ]
