# Generated by Django 6.0 on 2025-12-25 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_remove_project_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
